In [1]:
# Import Dependencies
import torch

### Resizing Tensors

In [2]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [3]:
# Size of "a"
a.size()

torch.Size([2, 2])

In [4]:
# Change 2,2 to 4
a.view(4)

tensor([1., 1., 1., 1.])

In [5]:
a.view(4).size()

torch.Size([4])

### Element wise Addition

In [6]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [7]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [8]:
# Add a and b
a + b * 2

tensor([[3., 3.],
        [3., 3.]])

In [9]:
# Add using torch
c = torch.add(a,b*2)
c

tensor([[3., 3.],
        [3., 3.]])

In [10]:
# In place addition
print("Old c tensor: \n",c)

c.add_(a*5)
print("\nNew c tensor: \n",c)

Old c tensor: 
 tensor([[3., 3.],
        [3., 3.]])

New c tensor: 
 tensor([[8., 8.],
        [8., 8.]])


### Element wise Subtraction

In [11]:
c - a

tensor([[7., 7.],
        [7., 7.]])

In [12]:
# Not in-place subtraction
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [13]:
# Original a unchanged
a

tensor([[1., 1.],
        [1., 1.]])

In [14]:
# In-place subtraction
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [15]:
# Value of a gets changed
a

tensor([[0., 0.],
        [0., 0.]])

### Element wise Multiplications

In [16]:
print(a)
print(b)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [17]:
(a + 1) * b * 2

tensor([[2., 2.],
        [2., 2.]])

In [18]:
c = torch.mul((a+1),b)
c

tensor([[1., 1.],
        [1., 1.]])

In [19]:
# In Place multiplication
b.mul_(a+2)

tensor([[2., 2.],
        [2., 2.]])

In [20]:
b

tensor([[2., 2.],
        [2., 2.]])

In [21]:
a

tensor([[0., 0.],
        [0., 0.]])

### Element wise Division

In [22]:
a = torch.ones(2,2)
b = torch.ones(2,2)

In [23]:
c = a.add(2)
c

tensor([[3., 3.],
        [3., 3.]])

In [24]:
print("Original a: \n",a)

a.add_(2)
print("\nIn place addition a: \n",a)

Original a: 
 tensor([[1., 1.],
        [1., 1.]])

In place addition a: 
 tensor([[3., 3.],
        [3., 3.]])


In [25]:
print("Original b: \n",b)

b.add_(3)
print("\nIn place addition b: \n",b)

Original b: 
 tensor([[1., 1.],
        [1., 1.]])

In place addition b: 
 tensor([[4., 4.],
        [4., 4.]])


In [26]:
# Divide not in place
d = b/a
d

tensor([[1.3333, 1.3333],
        [1.3333, 1.3333]])

In [27]:
d = b.div(a)
d

tensor([[1.3333, 1.3333],
        [1.3333, 1.3333]])

In [28]:
# Divide in Place
b.div_(a)

tensor([[1.3333, 1.3333],
        [1.3333, 1.3333]])

In [29]:
print(b)

tensor([[1.3333, 1.3333],
        [1.3333, 1.3333]])


In [30]:
print(a)

tensor([[3., 3.],
        [3., 3.]])


### Tensor Mean

In [31]:
a = torch.Tensor([2,6,4,1,4,3,5,8,10])
a

tensor([ 2.,  6.,  4.,  1.,  4.,  3.,  5.,  8., 10.])

In [32]:
a.size()

torch.Size([9])

In [33]:
# Mean of Tensor, dim=0 coz we have only one dimension here
a.mean(dim=0)

tensor(4.7778)

In [34]:
# Verifying mean using Numpy
import numpy as np

b = a.numpy()
b.mean()

4.7777777

In [35]:
# Multi dimeansional Tensor
a = torch.Tensor([[2,6,4,1,4,3,5,8,10], [2,6,4,1,4,3,5,8,10]])
a

tensor([[ 2.,  6.,  4.,  1.,  4.,  3.,  5.,  8., 10.],
        [ 2.,  6.,  4.,  1.,  4.,  3.,  5.,  8., 10.]])

In [36]:
# rows,cols
a.size()

torch.Size([2, 9])

In [37]:
# Mean along dimension 1 i.e 9 values in both lists
a.mean(dim=1)

tensor([4.7778, 4.7778])

### Tensor Standard Deviation

In [38]:
# Sample tensor
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
a.std(dim=0)

tensor(3.0277)